printWidth: 110
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: 'consistent'
jsxSingleQuote: false
trailingComma: 'es5'
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: 'avoid'



- name: generate-breakout-game-from-github-contribution-graph
  uses: cyprieng/github-breakout@v1.0.0
